precision: 32
max_epochs: 75
num_nodes: 1
accelerator: 
devices: 0
sync_batchnorm: True
default_root_dir: ${exp_dir}
num_sanity_val_steps: 0
accumulate_grad_batches: 1
gradient_clip_val: 5.0
use_distributed_sampler: False